### ISSUE TITLE
Syntax error with default HTTP listener example

### ISSUE THREAD

**Issue by digininja** [RocketChat/RocketBot#5]
I'm trying to get the HTTP listener working and just got a crash with a syntax error.

From the HTTP Listener section on this page:

https://hubot.github.com/docs/scripting/

I tried the JSON call and got this error:

```
# curl -X POST -H "Content-Type: application/json" -d '{"secret":"C-TECH Astronomy"}' http://127.0.0.1:8080/hubot/chatsecrets/general

SyntaxError: Unexpected token u
 at Object.parse (native)
 at /home/hubot/scripts/robin.coffee:79:15, <js>:70:19
 at callbacks (/home/hubot/node_modules/hubot/node_modules/express/lib/router/index.js:164:37)
 at param (/home/hubot/node_modules/hubot/node_modules/express/lib/router/index.js:138:11)
 at param (/home/hubot/node_modules/hubot/node_modules/express/lib/router/index.js:135:11)
 at pass (/home/hubot/node_modules/hubot/node_modules/express/lib/router/index.js:145:5)
 at Router._dispatch (/home/hubot/node_modules/hubot/node_modules/express/lib/router/index.js:173:5)
 at Object.router (/home/hubot/node_modules/hubot/node_modules/express/lib/router/index.js:33:10)
 at next (/home/hubot/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:174:15)
 at Object.multipart [as handle] (/home/hubot/node_modules/hubot/node_modules/connect-multiparty/index.js:42:27)
 at next (/home/hubot/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:174:15)
 at Object.urlencodedParser [as handle] (/home/hubot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/types/urlencoded.js:81:44)
 at next (/home/hubot/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:174:15)
 at /home/hubot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/read.js:121:5
 at invokeCallback (/home/hubot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
 at done (/home/hubot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
 at IncomingMessage.onEnd (/home/hubot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:307:7)
 at IncomingMessage.emit (events.js:104:17)
 at _stream_readable.js:908:16
 at process._tickCallback (node.js:355:11)
```

This is line 79 in robin.coffee:

```
77  robot.router.post '/hubot/chatsecrets/:room', (req, res) ->
78     room   = req.params.room
79     data   = JSON.parse req.body.payload
80     secret = data.secret

```

The raw HTTP POST works fine so I know the bot is up and listening OK:

```
# curl -d 'payload=%7B%22secret%22%3A%22C-TECH+Astronomy%22%7D' http://127.0.0.1:8080/hubot/chatsecrets/general
OK
```

Any ideas?

**Comment by geekgonecrazy** [comment]
I think in the past i've had to escape the json posted when using curl.  

`curl -X POST -H "Content-Type: application/json" -d '{\"secret\":\"C-TECH Astronomy\"}' http://127.0.0.1:8080/hubot/chatsecrets/general`

**Comment by digininja** [comment]
I think I tried that but I'll give it another try.

**Comment by digininja** [comment]
Thought I'd tried it, fails in a different way:

```
$ curl -X POST -H "Content-Type: application/json" -d '{\"secret\":\"C-TECH Astronomy\"}' http://127.0.0.1:8080/hubot/chatsecrets/general
SyntaxError: Unexpected token \<br> 
&nbsp;at Object.parse (native)<br> 
&nbsp;at parse (/home/hubot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/types/json.js:88:17)<br> 
&nbsp;at /home/hubot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/read.js:108:18<br> 
&nbsp;at invokeCallback (/home/hubot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:262:16)<br>
&nbsp;at done (/home/hubot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:251:7)<br> 
&nbsp;at IncomingMessage.onEnd (/home/hubot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:307:7)<br> 
&nbsp;at IncomingMessage.emit (events.js:104:17)<br> &nbsp;at _stream_readable.js:908:16<br>
&nbsp;at process._tickCallback (node.js:355:11)<br>
```

**Comment by geekgonecrazy** [comment]
I should have read better. 

So your initial way of posting is fine.  The issue is in the receiving code.

```
77  robot.router.post '/hubot/chatsecrets/:room', (req, res) ->
78     room   = req.params.room
79     data   = JSON.parse req.body.payload
80     secret = data.secret
```

when you send the post body of: `{"secret":"C-TECH Astronomy"}` its attempting to parse the `req.body.payload` which does not exist.  You'd want to parse just the body of the request: `req.body` then grab the property out of that.

So something like: 

```
robot.router.post '/hubot/chatsecrets/:room', (req, res) ->
   room   = req.params.room
   data   = JSON.parse req.body
   secret = data.secret
```

**Comment by geekgonecrazy** [comment]
If you wanted to make it optional to use either just a json payload, or `payload=%7B%22secret%22%3A%22C-TECH+Astronomy%22%7D` then you'd want to do a check to see if the payload property existed first.

So something like:

```
if req.body.payload?
    // parse req.body.payload
```

**Comment by digininja** [comment]
That makes sense now looking at the example code given on that page, thanks.

Would be handy if the bot could detect something like that and fail
gracefully rather than with a stack trace.

Just got my first call out, run script, call back in working so I'm
definitely making progress.

**Comment by geekgonecrazy** [comment]
Agreed they could have generated much more useful errors.

Awesome!  Glad you're figuring it out. 👍
